imports:
    - { resource: 'fixtures/shop_configuration.yaml' }
    - { resource: 'fixtures/tshirt.yaml' }
    - { resource: 'fixtures/cap.yaml' }
    - { resource: 'fixtures/dress.yaml' }
    - { resource: 'fixtures/jeans.yaml' }
    - { resource: 'fixtures/promotion.yaml' }
    - { resource: 'fixtures/custom_fixtures.yaml' }
